# Global Variables

title: More Tongues Than Teeth
description: A mish-mash of indie trash.
keywords:
  - band
  - music
  - rock
  - indie rock
  - Brooklyn
logo:
  svg: "/assets/logo.svg"
  png: "/assets/logo.png"
og_image: "/assets/temper-tantrum-og-2.jpg"
baseurl: ""
url: "http://www.moretongues.com"
google_analytics: "UA-101639062-1"
fb_page_id: "169341510228289"
contact:
  facebook: "https://www.facebook.com/MoreTonguesThanTeeth/"
  instagram: "https://www.instagram.com/moretonguesthanteeth"
  bandcamp: "https://moretongues.bandcamp.com/releases"
  youtube: "https://www.youtube.com/channel/UCXUKrkDX88zx1bL4Xu8qZYw"
  email: "moretonguesthanteeth@gmail.com"
temper_tantrum:
  bandcamp: "https://moretongues.bandcamp.com/album/temper-tantrum"
  apple_music: "https://geo.itunes.apple.com/us/album/temper-tantrum/1339448765?mt=1&app=music&itscg=30200&itsct=afftoolset_1"
  spotify: "https://open.spotify.com/album/2atIKJg8Z1BrjYpL4Wk56a"
permalink: /:title/
timezone: America/New_York
emptyArray: []

person_height: 84

image_bp:
  - x: 2880
    y: 1800
  - x: 2560
    y: 1600
  - x: 2160
    y: 1440
  - x: 1920
    y: 1200
  - x: 1400
    y: 900
  - x: 1280
    y: 800
  - x: 1024
    y: 768
  - x: 960
    y: 640
  - x: 800
    y: 480
  - x: 640
    y: 360
  - x: 480
    y: 320

# Build settings

markdown: kramdown
exclude:
  - "README.md"
  - "Gemfile*"
  - "node_modules"
  - "package*.json"
  - "gulpfile.js"
  - "assets/test"
