# Global Variables

title: Title of Your Site
description: >
  A subtitle or longer description of the site.
keywords: # a YAML list. optional; only used by some older search engines.
baseurl: # for hosting at a subdomain
url: # full url of main site
og_image: # default og image used for entire site; can be overridden if specified in page or collection frontmatter
google_analytics: # tracking number
permalink: /:title/ # default permalink structure for pages
timezone: America/New_York # used for liquid-generated datetimes
auto_scroll: false # enables smooth scrolling for all same-page links using zenscroll
native_scroll: false # enables smooth scrolling by the scroll-behavior property, for all browsers that support it
bg_testing: false # turn on to enable the bg-testing.html include
emptyArray: [] # variable for easy array creation

# Build settings

markdown: kramdown
exclude:
  - "README.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "package.json"
  - "package-lock.json"
  - "node_modules"
  - "gulpfile.js"
  - "assets/test"

# Prose

prose:
  ignore:
    - "*.html"
    - "*.svg"
    - "*.xml"
    - "*.liquid"
    - "*.js"
    - "*.json"
    - "*.jsonp"
    - "*.rb"
    - "*.sh"
    - "_layouts"
    - "_sass"
    - "_site"
    - "css"
    - "js"
    - "assets"
    - "_data/icon-types.yml"
    - "_includes/lorem-ipsum.md"
    - "_config*.yml"
    - "README.md"
    - ".*rc"
    - ".ruby-version"
    - ".nvmrc"
    - ".gitignore"
    - "Gemfile*"
