# Global Variables

title: Title of Your Site
description: >
  A subtitle or longer description of the site.
keywords: # a YAML list. optional; only used by some older search engines.
baseurl: # for hosting at a subdomain
url: "https://starter-test.netlify.com" # full url of main site
og_image: # default og image used for entire site; can be overridden if specified in page or collection frontmatter
google_analytics: # tracking number
permalink: /:title/ # default permalink structure for pages
copyright:
  date: 2019-05-31T17:24:00-4:00 # date the site was created
  owner: Site Owner # owner of the site

# Configuration

timezone: America/New_York # used for liquid-generated datetimes
auto_scroll: false # enables smooth scrolling for all same-page links using zenscroll
native_scroll: false # enables smooth scrolling by the scroll-behavior property, for all browsers that support it
bg_testing: false # turn on to enable the bg-testing.html include
emptyArray: [] # variable for easy array creation

# Collections

collections:
  comments:
    output: false
  templates:
    output: false

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: "/:year/:month/:day/:title/"

# Build settings

markdown: kramdown
exclude:
  - "README.md"
  - "Gemfile*"
  - "package*.json"
  - "node_modules"
  - "gulpfile.js"
  - "assets/test"
keep_files:
  - "assets"

plugins:
  - liquid-md5

jekyll_comments:
  branch: master
  collection: comments
  path: _comments
  api: # path to comments API

# Prose

prose:
  ignore:
    - "*.html"
    - "*.svg"
    - "*.xml"
    - "*.liquid"
    - "*.js"
    - "*.json"
    - "*.jsonp"
    - "*.rb"
    - "*.sh"
    - "_layouts"
    - "_sass"
    - "_site"
    - "css"
    - "js"
    - "assets"
    - "_data/icon-types.yml"
    - "_includes/lorem-ipsum.md"
    - "_config*.yml"
    - "README.md"
    - ".*rc"
    - ".ruby-version"
    - ".nvmrc"
    - ".gitignore"
    - "Gemfile*"
